- hosts: all
  roles:
    - prometheus.prometheus.node_exporter
    - prometheus.prometheus.prometheus
    - common

- hosts: web
  roles:
    - caddy

- hosts: weechat
  roles:
    - weechat

- hosts: beets
  roles:
    - samba
    - beet
    - mailer

- hosts: pihole
  roles:
    - pihole

- hosts: tailscale
  roles:
    - tailscale

- hosts: imagehost
  roles:
    - imagehost

- hosts: grafana
  roles:
    - prometheus.prometheus.prometheus
    - prometheus.prometheus.pushgateway
    - prometheus.prometheus.memcached_exporter
    - grafana

- hosts: minio
  roles:
    - geerlingguy.docker
    - minio

- hosts: pirate
  roles:
    - geerlingguy.docker
    - transmission

- hosts: gitlab
  roles:
    - geerlingguy.docker
    - gitlab_runner

- hosts: coolify
  roles:
    - geerlingguy.docker
    - coolify