---
- hosts: all
  roles:
    - common

- hosts: web
  roles:
    - caddy

- hosts: weechat
  roles:
    - weechat

- hosts: beets
  roles:
    - samba
    - beet

- hosts: pihole
  roles:
    - pihole

- hosts: homeassistant
  roles:
    - homeassistant