- hosts: all
  roles:
    - common

- hosts: namada
  roles:
    # - geerlingguy.docker
    - prometheus.prometheus.prometheus
    - role: namada_validator
      tags: [namada_validator]

- hosts: web
  roles:
    - caddy

- hosts: weechat
  roles:
    # - nordvpn
    - weechat

- hosts: beets
  roles:
    - samba
    - beet
    - mailer

- hosts: tailscale
  roles:
    - tailscale

- hosts: imagehost
  roles:
    - imagehost

- hosts: grafana
  roles:
    - prometheus.prometheus.prometheus
    - prometheus.prometheus.pushgateway
    - prometheus.prometheus.memcached_exporter
    - grafana

- hosts: minio
  roles:
    - geerlingguy.docker
    - minio

- hosts: pirate
  roles:
    - geerlingguy.docker
    - transmission

- hosts: gitlab
  roles:
    - geerlingguy.docker
    - gitlab_runner

- hosts: coolify
  roles:
    - geerlingguy.docker
    - coolify

- hosts: vpn
  roles:
    - nordvpn

- hosts: containers
  roles:
    - prometheus.prometheus.prometheus
    - role: geerlingguy.docker
      become: true
    - role: containers
      tags: ["containers"]
  tasks:
    - name: Create unrar script
      copy:
        dest: "{{ ansible_user_dir }}/unrar_all.sh"
        mode: "0755"

        content: |
          #!/bin/bash
          TARGET_DIR="/mnt/torrents/complete"

          set -a

          # Check if target directory exists
          if [ ! -d "$TARGET_DIR" ]; then
              echo "Error: Directory '$TARGET_DIR' does not exist"
              exit 1
          fi

          # Check if unrar is available
          if ! command -v unrar &> /dev/null; then
              echo "Error: unrar command not found. Please install unrar first."
              exit 1
          fi

          LOCKFILE="/tmp/unrar_subdirs.lock"
          PIDFILE="/tmp/unrar_subdirs.pid"

          # Function to clean up lockfile on exit
          cleanup() {
              echo "removing lockfile"
              rm -f "$LOCKFILE" "$PIDFILE"
          }


          if [ -f "$LOCKFILE" ]; then
              # Check if the process is still running
              if [ -f "$PIDFILE" ]; then
                  OLD_PID=$(cat "$PIDFILE")
                  if ps -p "$OLD_PID" > /dev/null 2>&1; then
                      echo "Error: Script is already running (PID: $OLD_PID)"
                      echo "If you're sure it's not running, remove: $LOCKFILE"
                      exit 1
                  else
                      echo "Removing stale lockfile (process $OLD_PID no longer exists)"
                      rm -f "$LOCKFILE" "$PIDFILE"
                  fi
              fi
          fi

          # Set trap to cleanup on exit
          trap cleanup EXIT INT TERM

          # Create lockfile and store our PID
          echo $$ > "$PIDFILE"
          touch "$LOCKFILE"

          find "$TARGET_DIR" -type f -name ".unrar" -print0 | while IFS= read -r -d '' unrar_file; do
              # Get the directory containing the .unrar file
              unrar_dir=$(dirname "$unrar_file")
              echo ".unrar in ${unrar_dir}"

              # Change to the directory and find nested .rar fils
              (
            cd "$unrar_dir" || exit 1

            # find all rar files in this dir and unrar them
            find "${unrar_dir}" -type f -name "*.rar" -print0 | while IFS= read -r -d '' rar_file; do
                dir=$(dirname $rar_file)
                (
              echo "rar file in ${dir}";
              cd "${dir}" || exit 1;
              pwd ;
                    temp_dir=$(mktemp -d -t unrar.XXXXXXXXXX);
                    unrar x "$(basename "$rar_file")" "$temp_dir/";

              # if unrar did not exit properly, abort and do not clean up
              unrar_exit=$?
              if ! [ $unrar_exit -eq 0 ]; then
                  echo "unrar did not exit properly";
                  exit $unrar_exit;
              else
                        mv "$temp_dir"/* "$dir/" 2>/dev/null;
                  rmdir "$temp_dir";
              fi;
                )
            done

            # if the unrar did not complete, do not remove the .unrar file
            exit_code=$?

            if ! [ $exit_code -eq 0 ]; then
              exit $exit_code;
            else
              rm .unrar;
            fi

              )
          done
    - name: Create cron job for script
      cron:
        name: "Unrar all torrents"
        minute: "*"
        hour: "*"
        job: "{{ ansible_user_dir }}/unrar_all.sh"
