# - hosts: all
#   roles:
#     - common

- hosts: namada
  roles:
    # - geerlingguy.docker
    - prometheus.prometheus.prometheus
    - role: namada_validator
      tags: [namada_validator]

- hosts: web
  roles:
    - caddy

- hosts: weechat
  roles:
    # - nordvpn
    - weechat

- hosts: beets
  roles:
    - samba
    - beet
    - mailer

- hosts: tailscale
  roles:
    - tailscale

- hosts: imagehost
  roles:
    - imagehost

- hosts: grafana
  roles:
    - prometheus.prometheus.prometheus
    - prometheus.prometheus.pushgateway
    - prometheus.prometheus.memcached_exporter
    - grafana

- hosts: minio
  roles:
    - geerlingguy.docker
    - minio

- hosts: pirate
  roles:
    - geerlingguy.docker
    - transmission

- hosts: gitlab
  roles:
    - geerlingguy.docker
    - gitlab_runner

- hosts: coolify
  roles:
    - geerlingguy.docker
    - coolify


- hosts: vpn
  roles:
    - nordvpn
