{
 "title": "System",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "query_result(sum by(host) (rate(node_network_transmit_bytes_total[$__range])))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Data Tx",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{host=\"$host\",device!~\"veth.*\", device!~\"tailscale.*\", device!~\"docker.*\", device!~\"lo\", device!~\"br.*\"}[$__rate_interval]) )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data Rx",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{host=\"$host\",device!~\"veth.*\", device!~\"tailscale.*\", device!~\"docker.*\", device!~\"lo\", device!~\"br.*\"}[$__rate_interval]) )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(node_filesystem_avail_bytes{host=\"$host\", fstype!=\"tmpfs\", mountpoint!=\"/boot/efi\", mountpoint!~\"/var/.*\", mountpoint!~\"/mnt/.*\", mountpoint!~\"/etc/.*\"}[1h]) / on(device, mountpoint) avg_over_time(node_filesystem_size_bytes{host=\"$host\", fstype!=\"tmpfs\", mountpoint!=\"/boot/efi\"}[1h])",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - avg by(host) (rate(node_cpu_seconds_total{mode=\"idle\", host=\"$host\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " 1 - (node_memory_MemAvailable_bytes{host=\"$host\"} / node_memory_MemTotal_bytes{host=\"$host\"} )"
    }
   ]
  },
  {
   "title": "Container States",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(state) (last_over_time(engine_daemon_container_states_containers{host=\"$host\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data Tx (Daily)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(node_network_transmit_bytes_total{host=\"$host\", device!~\"veth.*\", device!~\"tailscale.*\", device!~\"docker.*\", device!~\"lo\", device!~\"br.*\"}[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data Rx (Daily)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(node_network_receive_bytes_total{host=\"$host\", device!~\"veth.*\", device!~\"tailscale.*\", device!~\"docker.*\", device!~\"lo\", device!~\"br.*\"}[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": " (1 - avg by(host,cpu) (rate(node_cpu_seconds_total{host=\"$host\",mode=\"idle\"}[$__rate_interval])))  / on() group_left(host) count by(host) (node_cpu_seconds_total{host=\"$host\",mode=\"idle\"})",
     "legendFormat": "Core {{cpu}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{host=\"$host\",device!~\"veth.*\", device!~\"tailscale.*\", device!~\"docker.*\", device!~\"lo\", device!~\"br.*\"}[$__rate_interval]) )",
     "legendFormat": "TX"
    },
    {
     "expr": "sum(rate(node_network_receive_bytes_total{host=\"$host\",device!~\"veth.*\", device!~\"tailscale.*\", device!~\"docker.*\", device!~\"lo\", device!~\"br.*\"}[$__rate_interval]) )",
     "legendFormat": "RX"
    }
   ]
  },
  {
   "title": "Disk Usage Line",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (node_filesystem_avail_bytes{host=\"$host\", mountpoint!~\"/boot/.*\", mountpoint!~\"/var/.*\", mountpoint!~\"/mnt/.*\", mountpoint!~\"/etc/.*\", mountpoint!~\"/run.*\"} / node_filesystem_size_bytes{host=\"$host\", mountpoint!~\"/boot/.*\", mountpoint!~\"/var/.*\", mountpoint!~\"/mnt/.*\", mountpoint!~\"/etc/.*\", mountpoint!~\"/run.*\"})",
     "legendFormat": "{{device}} {{mountpoint}}"
    }
   ]
  }
 ]
}