{
 "title": "3D Printer",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   { "name": "kwh_cost", "label": "€/kWh", "query": "0.25" },
   { "name": "granularity", "label": "Range", "query": "1d,1w,1m,1y" }
  ]
 },
 "panels": [
  {
   "title": "Energy Cost This Year",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(homeassistant_sensor_energy_kwh{entity=\"sensor.office_prusa_energy\"}[$__range]) * $kwh_cost",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Printing Hours",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time((homeassistant_sensor_unit_percent{domain=\"sensor\", entity=\"sensor.prusa_mk4_progress\"} > bool 0)[1y:1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Consumption",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((increase(homeassistant_sensor_energy_kwh{entity=\"sensor.office_prusa_energy\"}[$__range]))) / sum(sum_over_time((homeassistant_sensor_unit_percent{domain=\"sensor\", entity=\"sensor.prusa_mk4_progress\"} > bool 0)[1y:1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cost/Hour",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((increase(homeassistant_sensor_energy_kwh{entity=\"sensor.office_prusa_energy\"}[$__range]) * $kwh_cost)) / sum(sum_over_time((homeassistant_sensor_unit_percent{domain=\"sensor\", entity=\"sensor.prusa_mk4_progress\"} > bool 0)[1y:1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Hours Per Day",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "expr": "(sum by (day) (count_over_time((homeassistant_sensor_unit_percent{domain=\"sensor\", entity=\"sensor.prusa_mk4_progress\"} > bool 0)[$granularity:1h]))) \nor vector(0)",
     "legendFormat": "Print Hours"
    }
   ]
  },
  {
   "title": "Daily Consumption",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "(increase(homeassistant_sensor_energy_kwh{entity=\"sensor.office_prusa_energy\"}[$granularity] offset -1h) and increase(homeassistant_sensor_energy_kwh{entity=\"sensor.office_prusa_energy\"}[$granularity] offset 23h))\n\n",
     "legendFormat": "Consumption"
    }
   ]
  },
  {
   "title": "Daily Cost",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": "(increase(homeassistant_sensor_energy_kwh{entity=\"sensor.office_prusa_energy\"}[$granularity] offset -1h) and increase(homeassistant_sensor_energy_kwh{entity=\"sensor.office_prusa_energy\"}[$granularity] offset 23h)) * $kwh_cost\n",
     "legendFormat": "Consumption"
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg(homeassistant_sensor_power_w{entity=\"sensor.office_prusa_power\"})",
     "legendFormat": "Power"
    }
   ]
  }
 ]
}