{
 "title": "Laadpaal",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Power",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_sensor_power_w{friendly_name=\"Garage - Metered Charge plug  Power\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Energy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_sensor_energy_kwh{friendly_name=\"Garage - Metered Charge plug  Energy\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Cost",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_sensor_energy_kwh{friendly_name=\"Garage - Metered Charge plug  Energy\"} * 0.35",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "homeassistant_sensor_power_w{friendly_name=\"Garage - Metered Charge plug  Power\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Energy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "delta(homeassistant_sensor_energy_kwh{friendly_name=\"Garage - Metered Charge plug  Energy\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Daily",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "homeassistant_sensor_energy_kwh{friendly_name=\"Garage - Metered Charge plug  Energy\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}