{
 "title": "Printer",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "bucket_size", "label": "Bucket Size", "query": "1h, 12h, 1d, 7d, 31d" }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_sensor_power_w{friendly_name!~\"(SB.*|energyhome.*)\"}",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Energy Cost",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_sensor_energy_kwh * 0.25",
     "legendFormat": "{{entity}}"
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "homeassistant_sensor_power_w{friendly_name!~\"SB5.*|energyhome.*\"}",
     "legendFormat": "{{ friendly_name }}"
    }
   ]
  },
  {
   "title": "Energy",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "increase(homeassistant_sensor_energy_kwh[1h])",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Energy Totals",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "homeassistant_sensor_energy_kwh",
     "legendFormat": "{{entity}}"
    }
   ]
  },
  {
   "title": "Energy Cost",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": "homeassistant_sensor_energy_kwh * 0.25",
     "legendFormat": "{{entity}}"
    }
   ]
  }
 ]
}