{
 "title": "Data Api",
 "tags": [
  "loomy",
  "data-api"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Task Duration",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg_over_time({compose_service=\"data-api\", host=\"$host\"} | json | message_module =~ `DataApi.*` | unwrap message_max [5m]) by (message_label) / 1000",
     "legendFormat": "{{ message_label }}"
    }
   ]
  },
  {
   "title": "Message Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg_over_time({compose_service=\"data-api\", host=\"$host\"} |= `data_handle_message` | json | message_label = `:data_handle_message` | unwrap message_count | __error__=`` [5m]) by (message_label)",
     "legendFormat": "{{message_label}}"
    },
    {
     "direction": "backward",
     "expr": "avg_over_time({compose_service=\"data-api\", host=\"$host\"} |= `data_handle_message` | json | message_label = `:data_handle_message` | unwrap message_count | __error__=`` [6h]) by (message_label)",
     "legendFormat": "{{message_label}} 1h"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg_over_time({compose_service=\"data-api\", host=\"$host\"} |= `data_handle_message` | json | message_label = `:data_handle_message` | unwrap message_avg | __error__=`` [1m]) by (message_label) / 1000",
     "legendFormat": "Average"
    },
    {
     "expr": "max_over_time({compose_service=\"data-api\", host=\"$host\"} |= `data_handle_message` | json | message_label = `:data_handle_message` | unwrap message_max | __error__=`` [1m]) by (message_label) / 1000",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Ingester Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "direction": "backward",
     "expr": "max_over_time({compose_project=\"loomy-services\", host=\"$host\"} |= `ingester_queue` | json | unwrap message_ingester_queue | __error__=`` [$__auto]) by (compose_project)",
     "legendFormat": "Queue"
    },
    {
     "direction": "backward",
     "expr": "max_over_time({compose_project=\"loomy-services\", host=\"$host\"} |= `worker_count` | json | unwrap message_worker_count | __error__=`` [$__auto]) by (compose_project)",
     "legendFormat": "Workers"
    }
   ]
  }
 ]
}