{
 "title": "Logs",
 "tags": [
  "loomy",
  "logs"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Error", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Error",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{compose_project=\"loomy-services\", service_name!~\"loomy-services-mqtt-1\", host=\"$host\"} |= `\"severity\":\"error\"` or `error` != `\"severity\":\"info\"` or `\"severity\":\"warning\"`"
    }
   ]
  },
  { "title": "Warning", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Warning",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{compose_project=\"loomy-services\", host=\"$host\"} |= `warn`"
    }
   ]
  },
  { "title": "Regular", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Regular",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{compose_project=\"loomy-services\", host=\"$host\"} != `error` or `warning`"
    }
   ]
  }
 ]
}