#SPDX-License-Identifier: MIT-0
---
- name: create minio data directory
  ansible.builtin.file:
    path: "/root/.minio"
    state: directory
    owner: 1001
    group: 1001
    mode: 0777

- name: create minio container
  community.docker.docker_container:
    name: minio
    # after this image the web ui is broken, so keep this version around.
    image: bitnami/minio:2025.4.22
    ports:
      - "9000:9000"
      - "9001:9001"
    env:
        MINIO_PROMETHEUS_AUTH_TYPE: "public"
        MINIO_DEFAULT_BUCKETS: "mimir-blocks-storage,mimir-ruler-storage,loki-common,loki-storage"
    volumes:
      # - /root/.minio:/bitnami/minio/data
      - /mnt/data/.minio:/bitnami/minio/data
