
- name: install packages
  include_tasks: packages.yml
  tags: packages

- name: configure ntp
  include_tasks: ntp.yml
  tags: ntp

- name: configure nfs mounts
  include_tasks: nfs.yml
  tags: nfs


# - name: configure prometheus
#   include_tasks: prometheus.yml
#   tags: prometheus-config


# https://stackoverflow.com/questions/9457233/unlimited-bash-history
- name: set bash history
  blockinfile:
    path: "$HOME/.bashrc"
    block: |
      export HISTFILESIZE=
      export HISTSIZE=
      export HISTTIMEFORMAT="[%F %T] "
      export HISTFILE=~/.bash_eternal_history
      PROMPT_COMMAND="history -a; $PROMPT_COMMAND"
    state: present
    create: true

#---------------------------------------------------------------------------
# Locale

- block:
    - name: ensure localisation files for '{{ system_locale }}' are available
      locale_gen:
        name: "{{ system_locale }}"
        state: present

    - name: get current locale and language configuration
      command: localectl status
      register: locale_status
      changed_when: false

    - name: parse 'lang' from current locale and language configuration
      set_fact:
        locale_lang: "{{ locale_status.stdout | regex_search('LANG=([^\n]+)', '\\1') | first }}"

    - name: parse 'language' from current locale and language configuration
      set_fact:
        locale_language: "{{ locale_status.stdout | regex_search('LANGUAGE=([^\n]+)', '\\1') | default([locale_lang], true) | first }}"

    - name: configure locale to '{{ system_locale }}' and language to '{{ system_language }}'
      command: localectl set-locale LANG={{ system_locale }} LANGUAGE={{ system_language }}
      changed_when: locale_lang != system_locale or locale_language != system_language

  become: true
