- name: create mountpoints for nfs
  ansible.builtin.file:
    path: "{{ item.mountpoint }}"
    state: directory
  with_items: "{{ nfs_mounts }}"

- name: ensure all nfs mounts are defined
  ansible.posix.mount:
    src: "{{ item.src}}:{{ item.path }}"
    path: "{{ item.mountpoint }}"
    opts: "{{ item.opts }}"
    state: present
    fstype: nfs
  with_items: "{{ nfs_mounts }}"

- name: mount all nfs mounts
  ansible.posix.mount:
    src: "{{ item.src}}:{{ item.path }}"
    path: "{{ item.mountpoint }}"
    opts: "{{ item.opts }}"
    state: present
    fstype: nfs
  with_items: "{{ nfs_mounts }}"