---

- name: check if ntp has to be installed
  set_fact:
    install_ntp: no
  
- name: check if ntp has to be installed
  set_fact:
    install_ntp: yes
  when: ntp is defined and ntp.enabled is defined and ntp.enabled


- name: be sure ntp is installed
  apt:
    name: ntp
    state: present
  when: install_ntp
  tags: ntp

- name: be sure ntp is configured
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  notify:
    - restart ntpd
  when: install_ntp
  tags: ntp

- name: be sure ntpd is running and enabled
  ansible.builtin.service:
    name: ntp
    state: started
    enabled: true
  when: install_ntp
  tags: ntp