- block:
    - name: upgrade all packages
      ansible.builtin.apt:
        upgrade: dist

    - name: install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: debug
      debug:
        msg: "packages {{ default_packages }}"
    - name: install basic system packages
      apt:
        pkg: "{{ item }}"
        state: latest
        update_cache: true
      when: packages is defined
      with_items: "{{ default_packages }}"
  become: true
