- block:
  - name: ensure /etc/prometheus directory exists
    ansible.builtin.file:
      path: /etc/prometheus
      state: directory
      owner: prometheus
      group: prometheus
      mode: 0744

  - name: copy prometheus.yml to /etc/prometheus/prometheus.yml
    ansible.builtin.template:
      src: prometheus.yml.j2
      dest: /etc/prometheus/prometheus.yml
      owner: prometheus
      group: prometheus
      mode: 0744

  - name: make sure 'prometheus' service is started and enabled
    systemd:
      name: prometheus
      state: restarted
      enabled: yes
      daemon_reload: yes
  become: true