#-------------------------------------------------------------------------------
# role: common

packages:
  - curl
  - wget
  - tmux
  - git

nfs_mounts:
  - src: pulsar.localdomain
    path: /volume1/music
    opts: rw,sync,hard
    state: mounted
    fstype: nfs
    mountpoint: /mnt/music

#-------------------------------------------------------------------------------
# role: coolify

coolify_root: "{{ secret.coolify.root }}"
coolify_pass: "{{ secret.coolify.pass }}"
coolify_email: "{{ secret.coolify.email }}"