---
#-------------------------------------------------------------------------------
# role: common

default_packages:
  - apt-transport-https
  - software-properties-common
  - wget
  - curl
  - tar
  - zip
  - gpg
  - htop
  - tmux

#-------------------------------------------------------------------------------
# role: grafana

s3_endpoint: minio.isolated:9000
s3_access_key: "{{ secret.s3.access_key }}"
s3_secret_key: "{{ secret.s3.secret_key }}"
s3_insecure: true
s3_region: us-west

home_assistant_url: "homeassistant.call-cc.be"
home_assistant_key: "{{ secret.ha.token }}"

root_url: "observability.call-cc.be"

data_sources:
  - name: Loki
    type: loki
    access: proxy
    url: http://localhost:3100
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://localhost:8086
    database: influxdb
  - name: Mimir
    type: prometheus
    access: proxy
    url: http://localhost:9009/prometheus
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090