---
- name: pyenv
  include_tasks: pyenv.yml
  tags: pyenv

- name: delete old venv if exists
  file:
    path: "$HOME/venv"
    state: absent
  # when: homeassistant.force_pyenv

- name: Ensure the virtual environment exists
  shell: "python -m venv $HOME/venv"
  args:
    executable: /bin/bash

- name: install pip packages
  shell: "source $HOME/venv/bin/activate && pip install {{ item }}"
  args:
    executable: /bin/bash
  with_items:
    - "wheel"
    - "homeassistant==2024.10.4"

- name: create run_ha.sh
  lineinfile:
    path: "$HOME/run_ha.sh"
    create: true
    line: |
      #!/bin/bash
      source $HOME/venv/bin/activate
      hass

- name: start homeassistant in a tmux on boot
  ansible.builtin.cron:
    name: "start homeassistant"
    special_time: reboot
    job: "tmux new-session -d -s homeassistant '/usr/bin/tmux new-session -d bash /root/run.sh'"
