---
- name: remove previous .pyenv
  file: 
    path: "$HOME/.pyenv"
    state: absent
  when: homeassistant.force_pyenv

- name: download pyenv installer
  get_url: 
    url: https://pyenv.run
    dest: /tmp/pyenv.sh
    mode: 'a+x'
  when: homeassistant.force_pyenv

- name: run pyenv installer
  shell: /tmp/pyenv.sh
  when: homeassistant.force_pyenv

- name: remove pyenv installer
  file: 
    path: /tmp/pyenv.sh
    state: absent
  when: homeassistant.force_pyenv

- name: update .profile
  lineinfile:
    path: "$HOME/.profile"
    line: "{{ item }}"
    create: true
  with_items: 
    - 'export PYENV_ROOT="$HOME/.pyenv"'
    - 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"'
    - 'eval "$(pyenv init -)"'

- name: update .bash_profile
  lineinfile:
    path: "$HOME/.bash_profile"
    line: "{{ item }}"
    create: true
  with_items: 
    - 'export PYENV_ROOT="$HOME/.pyenv"'
    - 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"'
    - 'eval "$(pyenv init -)"'

- name: update .bashrc
  lineinfile:
    path: "$HOME/.bashrc"
    line: "{{ item }}"
    create: true
  with_items: 
    - 'export PYENV_ROOT="$HOME/.pyenv"'
    - 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"'
    - 'eval "$(pyenv init -)"'

- name: update /etc/environment
  lineinfile:
    path: "/etc/environment"
    line: "{{ item }}"
    create: true
  with_items: 
    - 'export PYENV_ROOT="$HOME/.pyenv"'
    - 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"'
    - 'eval "$(pyenv init -)"'

- name: install python 3.12 
  shell: "pyenv install --skip-existing {{ homeassistant.python_version }}"
  args:
    executable: /bin/bash

- name: install python 3.12 
  ansible.builtin.shell: "pyenv global {{ homeassistant.python_version }}"
  args:
    executable: /bin/bash
